// namespace Elements {
//     export const doge: string = '4paR4paR4paR4paR4paR4paR4paR4paR4paR4paE4paR4paR4paR4paR4paR4paR4paR4paR4paR4paR4paR4paR4paR4paR4paECuKWkeKWkeKWkeKWkeKWkeKWkeKWkeKWkeKWjOKWkuKWiOKWkeKWkeKWkeKWkeKWkeKWkeKWkeKWkeKWkeKWkeKWkeKWhOKWgOKWkuKWjArilpHilpHilpHilpHilpHilpHilpHilpHilozilpLilpLilojilpHilpHilpHilpHilpHilpHilpHilpHiloTiloDilpLilpLilpLilpAK4paR4paR4paR4paR4paR4paR4paR4paQ4paE4paA4paS4paS4paA4paA4paA4paA4paE4paE4paE4paA4paS4paS4paS4paS4paS4paQCuKWkeKWkeKWkeKWkeKWkeKWhOKWhOKWgOKWkuKWkeKWkuKWkuKWkuKWkuKWkuKWkuKWkuKWkuKWkuKWiOKWkuKWkuKWhOKWiOKWkuKWkArilpHilpHilpHiloTiloDilpLilpLilpLilpHilpHilpHilpLilpLilpLilpHilpHilpHilpLilpLilpLiloDilojilojiloDilpLilowK4paR4paR4paQ4paS4paS4paS4paE4paE4paS4paS4paS4paS4paR4paR4paR4paS4paS4paS4paS4paS4paS4paS4paA4paE4paS4paS4paMCuKWkeKWkeKWjOKWkeKWkeKWjOKWiOKWgOKWkuKWkuKWkuKWkuKWkuKWhOKWgOKWiOKWhOKWkuKWkuKWkuKWkuKWkuKWkuKWkuKWiOKWkuKWkArilpHilpDilpHilpHilpHilpLilpLilpLilpLilpLilpLilpLilpLilozilojilojiloDilpLilpLilpHilpHilpHilpLilpLilpLiloDiloTilowK4paR4paM4paR4paS4paE4paI4paI4paE4paS4paS4paS4paS4paS4paS4paS4paS4paS4paR4paR4paR4paR4paR4paR4paS4paS4paS4paS4paMCuKWjOKWkuKWgOKWkOKWhOKWiOKWhOKWiOKWjOKWhOKWkeKWgOKWkuKWkuKWkeKWkeKWkeKWkeKWkeKWkeKWkeKWkeKWkeKWkeKWkuKWkuKWkuKWkArilpDilpLilpLilpDiloDilpDiloDilpLilpHiloTiloTilpLiloTilpLilpLilpLilpLilpLilpLilpHilpLilpHilpLilpHilpLilpLilpLilpLilowK4paQ4paS4paS4paS4paA4paA4paE4paE4paS4paS4paS4paE4paS4paS4paS4paS4paS4paS4paS4paS4paR4paS4paR4paS4paR4paS4paS4paQCuKWkeKWjOKWkuKWkuKWkuKWkuKWkuKWkuKWgOKWgOKWgOKWkuKWkuKWkuKWkuKWkuKWkuKWkeKWkuKWkeKWkuKWkeKWkuKWkeKWkuKWkuKWkuKWjArilpHilpDilpLilpLilpLilpLilpLilpLilpLilpLilpLilpLilpLilpLilpLilpLilpHilpLilpHilpLilpHilpLilpLiloTilpLilpLilpAK4paR4paR4paA4paE4paS4paS4paS4paS4paS4paS4paS4paS4paS4paS4paS4paR4paS4paR4paS4paR4paS4paE4paS4paS4paS4paS4paMCuKWkeKWkeKWkeKWkeKWgOKWhOKWkuKWkuKWkuKWkuKWkuKWkuKWkuKWkuKWkuKWkuKWhOKWhOKWhOKWgOKWkuKWkuKWkuKWkuKWhOKWgArilpHilpHilpHilpHilpHilpHiloDiloTiloTiloTiloTiloTiloTiloDiloDiloDilpLilpLilpLilpLilpLiloTiloTiloAK4paR4paR4paR4paR4paR4paR4paR4paR4paR4paS4paS4paS4paS4paS4paS4paS4paS4paS4paS4paA4paA';
// }
System.register([], function (exports_1, context_1) {
    "use strict";
    var dupa;
    var __moduleName = context_1 && context_1.id;
    return {
        setters: [],
        execute: function () {
            exports_1("dupa", dupa = "dupa......");
        }
    };
});
